apiVersion: v1
kind: PersistentVolume
metadata:
  name: geth-nfs
  labels:
    volume: geth-client-volume
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
      storage: 5Gi
  persistentVolumeReclaimPolicy: Retain 
  nfs:
    path: /opt/nfs/geth-client
    server: k8smaster.local
