apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geth-client-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      volume: geth-client-volume
