apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-nfs
  labels:
    volume: mongodb-volume
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  nfs:
    path: /opt/nfs/mongodb
    server: k8smaster.local
    

    
